apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata: 
      labels: 
        app: backend
    spec:
      containers:
       - name: backend
         image: 440422120931.dkr.ecr.ap-south-1.amazonaws.com/ecommerce_backend:latest
         ports:
          - containerPort: 3000
         envFrom:
            - configMapRef:
                name: postgres-config        
